site_name: SQLAlchemy Admin
site_description: An admin dashboard for SQLAlchemy.

theme:
    name: 'material'

repo_name: sqlalchemy-admin/sqlalchemy-admin
repo_url: https://github.com/sqlalchemy-admin/sqlalchemy-admin
edit_uri: ""

# nav:
#     - Introduction: 'index.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - mkautodoc

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'
